### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by iimog** [phagewebufpa/API#1]
When running `phageweb.py` on my system I get this error message:
```
phageweb.py my_genome.gb 60 6
[...]
curl: (7) Failed to connect to 200.239.92.140 port 5000: Connection refused
[...]
```
Is there a firewall blocking connections to your server on port 5000? If so, is there a way to get past this restriction?

**Comment by iimog** [comment]
Update: after the whole PhageWeb page was not reachable for a couple of days and is back up now, I retried. Now I get this error message:
```
phageweb.py my_genome.gb 60 6
[...]
curl: (7) Failed to connect to 200.239.92.140 port 5000: Connection timed out
[...]
```
So the connection is no longer refused but now it times out.

**Comment by DNADoubleFelix** [comment]
I also get a connected timed out with some extra info that I'll copy here if it's useful:

`python3 phageweb.py ../input/pseudo/P_aeruginosa_PAO1_107.gbk 80 6`
`[...]`
`curl: (7) Failed to connect to 200.239.92.140 port 5000: Connection timed out `
`Traceback (most recent call last):`
`  File "phageweb.py", line 39, in <module>`
`    os.system("wget -c http://computationalbiology.ufpa.br/phageweb/analysis/api/" + id + "/output_tabular.tab")`
`TypeError: must be str, not bytes`

I also tried the web interface on the website and the connection also timed out there.

**Comment by phagewebufpa** [comment]
Hello, we're very sorry for the PhageWeb API. We had technical problems and the API needed to be modified. Please use the PhageWeb API (https://github.com/phagewebufpa/API).

Sorry for the delay in answering. We appreciate the interest and we are available for questions.

**Comment by iimog** [comment]
Thanks a lot for fixing the API.
